export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const LISTADO_PRODUCTOS = 'LISTADO_PRODUCTOS';
export const LISTADO_PRODUCTOS_EXITO = 'LISTADO_PRODUCTOS_EXITO';
export const LISTADO_PRODUCTOS_ERROR = 'LISTADO_PRODUCTOS_ERROR';

export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR';
export const PRODCUTO_ELIMINADO_EXITO = 'PRODCUTO_ELIMINADO_EXITO';
export const PRODCUTO_ELIMINADO_ERROR = 'PRODCUTO_ELIMINADO_ERROR';

export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR';
export const PRODCUTO_EDITADO_EXITO = 'PRODCUTO_EDITADO_EXITO';
export const PRODCUTO_EDITADO_ERROR = 'PRODCUTO_EDITADO_ERROR';
export const COMENZAR_EDICION_PRODUCTO = 'COMENZAR_EDICION_PRODUCTO';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';