// TYPES PARA PRODUCTOS
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const LISTADO_PRODUCTOS = 'LISTADO_PRODUCTOS';
export const LISTADO_PRODUCTOS_EXITO = 'LISTADO_PRODUCTOS_EXITO';
export const LISTADO_PRODUCTOS_ERROR = 'LISTADO_PRODUCTOS_ERROR';

export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINADO_EXITO = 'PRODUCTO_ELIMINADO_EXITO';
export const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR';

export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR';
export const PRODUCTO_EDITADO_EXITO = 'PRODUCTO_EDITADO_EXITO';
export const PRODUCTO_EDITADO_ERROR = 'PRODUCTO_EDITADO_ERROR';
export const COMENZAR_EDICION_PRODUCTO = 'COMENZAR_EDICION_PRODUCTO';

// TYPES PARA ALERTAS
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

// TYPES PARA USUARIOS Y SINGUP
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO';
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR';

export const LISTADO_USUARIOS = 'LISTADO_USUARIOS';
export const LISTADO_USUARIOS_EXITO = 'LISTADO_USUARIOS_EXITO';
export const LISTADO_USUARIOS_ERROR = 'LISTADO_USUARIOS_ERROR';

export const OBTENER_USUARIO_ELIMINAR = 'OBTENER_USUARIO_ELIMINAR';
export const USUARIO_ELIMINADO_EXITO = 'USUARIO_ELIMINADO_EXITO';
export const USUARIO_ELIMINADO_ERROR = 'USUARIO_ELIMINADO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';

// TYPES PARA ORDERNES DE COMPRA
export const AGREGAR_ORDEN_COMPRA = 'AGREGAR_ORDEN_COMPRA';
export const AGREGAR_ORDEN_COMPRA_EXITO = 'AGREGAR_ORDEN_COMPRA_EXITO';
export const AGREGAR_ORDEN_COMPRA_ERROR = 'AGREGAR_ORDEN_COMPRA_ERROR';

export const LISTADO_ORDEN_COMPRA = 'LISTADO_ORDEN_COMPRA';
export const LISTADO_ORDEN_COMPRA_EXITO = 'LISTADO_ORDEN_COMPRA_EXITO';
export const LISTADO_ORDEN_COMPRA_ERROR = 'LISTADO_ORDEN_COMPRA_ERROR';

export const OBTENER_ORDEN_COMPRA_ELIMINAR = 'OBTENER_ORDEN_COMPRA_ELIMINAR';
export const ORDEN_COMPRA_ELIMINADO_EXITO = 'ORDEN_COMPRA_ELIMINADO_EXITO';
export const ORDEN_COMPRA_ELIMINADO_ERROR = 'ORDEN_COMPRA_ELIMINADO_ERROR';
export const OBTENER_ORDEN_COMPRA = 'OBTENER_ORDEN_COMPRA';

// TYPES PARA Iniciar sesion
export const SINGIN = 'SINGIN';
export const SINGIN_EXITO = 'SINGIN_EXITO';
export const SINGIN_ERROR = 'SINGIN_ERROR';

// TYPES PARA Cerrar sesión
export const SINGOUT = 'SINGOUT';
export const SINGOUT_EXITO = 'SINGOUT_EXITO';
export const SINGOUT_ERROR = 'SINGOUT_ERROR';